// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmos/das/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRequestDAS struct {
	Requester       string `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty" Requester`
	BatchHeaderHash string `protobuf:"bytes,2,opt,name=batch_header_hash,json=batchHeaderHash,proto3" json:"batch_header_hash,omitempty"`
	NumBlobs        uint32 `protobuf:"varint,3,opt,name=num_blobs,json=numBlobs,proto3" json:"num_blobs,omitempty"`
}

func (m *MsgRequestDAS) Reset()         { *m = MsgRequestDAS{} }
func (m *MsgRequestDAS) String() string { return proto.CompactTextString(m) }
func (*MsgRequestDAS) ProtoMessage()    {}
func (*MsgRequestDAS) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2f96adc8b236fc, []int{0}
}
func (m *MsgRequestDAS) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestDAS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestDAS.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestDAS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestDAS.Merge(m, src)
}
func (m *MsgRequestDAS) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestDAS) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestDAS.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestDAS proto.InternalMessageInfo

type MsgRequestDASResponse struct {
	RequestID uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *MsgRequestDASResponse) Reset()         { *m = MsgRequestDASResponse{} }
func (m *MsgRequestDASResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestDASResponse) ProtoMessage()    {}
func (*MsgRequestDASResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2f96adc8b236fc, []int{1}
}
func (m *MsgRequestDASResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestDASResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestDASResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestDASResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestDASResponse.Merge(m, src)
}
func (m *MsgRequestDASResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestDASResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestDASResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestDASResponse proto.InternalMessageInfo

type MsgReportDASResult struct {
	RequestID uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Sampler   string `protobuf:"bytes,2,opt,name=sampler,proto3" json:"sampler,omitempty"`
	Success   bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgReportDASResult) Reset()         { *m = MsgReportDASResult{} }
func (m *MsgReportDASResult) String() string { return proto.CompactTextString(m) }
func (*MsgReportDASResult) ProtoMessage()    {}
func (*MsgReportDASResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2f96adc8b236fc, []int{2}
}
func (m *MsgReportDASResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReportDASResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReportDASResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReportDASResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReportDASResult.Merge(m, src)
}
func (m *MsgReportDASResult) XXX_Size() int {
	return m.Size()
}
func (m *MsgReportDASResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReportDASResult.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReportDASResult proto.InternalMessageInfo

type MsgReportDASResultResponse struct {
}

func (m *MsgReportDASResultResponse) Reset()         { *m = MsgReportDASResultResponse{} }
func (m *MsgReportDASResultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgReportDASResultResponse) ProtoMessage()    {}
func (*MsgReportDASResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2f96adc8b236fc, []int{3}
}
func (m *MsgReportDASResultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgReportDASResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgReportDASResultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgReportDASResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReportDASResultResponse.Merge(m, src)
}
func (m *MsgReportDASResultResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgReportDASResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReportDASResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReportDASResultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRequestDAS)(nil), "evmos.das.v1.MsgRequestDAS")
	proto.RegisterType((*MsgRequestDASResponse)(nil), "evmos.das.v1.MsgRequestDASResponse")
	proto.RegisterType((*MsgReportDASResult)(nil), "evmos.das.v1.MsgReportDASResult")
	proto.RegisterType((*MsgReportDASResultResponse)(nil), "evmos.das.v1.MsgReportDASResultResponse")
}

func init() { proto.RegisterFile("evmos/das/v1/tx.proto", fileDescriptor_8f2f96adc8b236fc) }

var fileDescriptor_8f2f96adc8b236fc = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x8e, 0x94, 0x40,
	0x14, 0xa5, 0x1c, 0xa3, 0x43, 0x45, 0x32, 0xb1, 0xe2, 0x24, 0x0c, 0x63, 0xb0, 0x83, 0x9b, 0xf6,
	0x11, 0x2a, 0xad, 0x89, 0x7b, 0xc9, 0x18, 0x67, 0x16, 0xe3, 0x02, 0x77, 0x26, 0x86, 0x14, 0x50,
	0x16, 0x9d, 0x00, 0x85, 0x5c, 0x20, 0xd3, 0x1f, 0xe0, 0xde, 0x8f, 0xf1, 0x23, 0x7a, 0xd9, 0x4b,
	0x57, 0x46, 0xe9, 0x3f, 0xf0, 0x0b, 0x4c, 0x17, 0xd0, 0xdd, 0xa8, 0xd1, 0xcc, 0x86, 0x70, 0xce,
	0xb9, 0x75, 0xee, 0xb9, 0x55, 0x17, 0x1f, 0xf3, 0x26, 0x93, 0x40, 0x63, 0x06, 0xb4, 0x99, 0xd1,
	0xea, 0xca, 0x2d, 0x4a, 0x59, 0x49, 0x72, 0x47, 0xd1, 0x6e, 0xcc, 0xc0, 0x6d, 0x66, 0xd6, 0x49,
	0x24, 0x21, 0x93, 0x10, 0x28, 0x8d, 0x76, 0xa0, 0x2b, 0xb4, 0xee, 0x09, 0x29, 0x64, 0xc7, 0x6f,
	0xfe, 0x7a, 0xf6, 0x44, 0x48, 0x29, 0x52, 0x4e, 0x15, 0x0a, 0xeb, 0x0f, 0x94, 0xe5, 0x8b, 0x5e,
	0xb2, 0x46, 0x0d, 0x05, 0xcf, 0x39, 0xcc, 0x7b, 0x33, 0xe7, 0x13, 0xc2, 0xc6, 0x25, 0x08, 0x9f,
	0x7f, 0xac, 0x39, 0x54, 0x67, 0x2f, 0xdf, 0x92, 0x27, 0x58, 0x2f, 0x3b, 0xc4, 0x4b, 0x13, 0x4d,
	0xd0, 0x54, 0xf7, 0x8c, 0x9f, 0xdf, 0x1e, 0xe8, 0xfe, 0x40, 0xfa, 0x3b, 0x9d, 0x3c, 0xc6, 0x77,
	0x43, 0x56, 0x45, 0x49, 0x90, 0x70, 0x16, 0xf3, 0x32, 0x48, 0x18, 0x24, 0xe6, 0x8d, 0xcd, 0x21,
	0xff, 0x48, 0x09, 0xe7, 0x8a, 0x3f, 0x67, 0x90, 0x90, 0x53, 0xac, 0xe7, 0x75, 0x16, 0x84, 0xa9,
	0x0c, 0xc1, 0x3c, 0x98, 0xa0, 0xa9, 0xe1, 0x1f, 0xe6, 0x75, 0xe6, 0x6d, 0xb0, 0xf3, 0x0a, 0x1f,
	0x8f, 0x62, 0xf8, 0x1c, 0x0a, 0x99, 0x03, 0x27, 0x4f, 0x31, 0xee, 0xdb, 0x05, 0xf3, 0x58, 0xe5,
	0xb9, 0xe9, 0x19, 0xed, 0x2e, 0xcf, 0xc5, 0xd9, 0x36, 0xcf, 0x45, 0xec, 0x34, 0x98, 0x28, 0x9b,
	0x42, 0x96, 0xbd, 0x4b, 0x9d, 0x56, 0xd7, 0xf3, 0x20, 0x26, 0xbe, 0x0d, 0x2c, 0x2b, 0x52, 0x5e,
	0xf6, 0x93, 0x0c, 0x50, 0x29, 0x75, 0x14, 0x71, 0xe8, 0xf2, 0x1f, 0xfa, 0x03, 0x74, 0xee, 0x63,
	0xeb, 0xcf, 0xbe, 0xc3, 0x0c, 0xcf, 0xbe, 0x20, 0x7c, 0x70, 0x09, 0x82, 0xbc, 0xc1, 0x78, 0xef,
	0xa2, 0x4f, 0xdd, 0xfd, 0x17, 0x77, 0x47, 0xe3, 0x5b, 0x0f, 0xff, 0x21, 0x6e, 0xef, 0xe6, 0x3d,
	0x3e, 0xfa, 0x7d, 0xd4, 0xc9, 0x5f, 0xce, 0x8d, 0x2a, 0xac, 0xe9, 0xff, 0x2a, 0x06, 0x7b, 0xef,
	0xf5, 0xf2, 0x87, 0xad, 0x2d, 0x5b, 0x1b, 0xad, 0x5a, 0x1b, 0x7d, 0x6f, 0x6d, 0xf4, 0x79, 0x6d,
	0x6b, 0xab, 0xb5, 0xad, 0x7d, 0x5d, 0xdb, 0xda, 0xbb, 0x47, 0x62, 0x5e, 0x25, 0x75, 0xe8, 0x46,
	0x32, 0xa3, 0xdd, 0x82, 0x75, 0xdf, 0x66, 0xf6, 0x82, 0x5e, 0x6d, 0xb7, 0x7b, 0x51, 0x70, 0x08,
	0x6f, 0xa9, 0x5d, 0x7b, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x60, 0x01, 0x24, 0x06, 0xfa, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RequestDAS(ctx context.Context, in *MsgRequestDAS, opts ...grpc.CallOption) (*MsgRequestDASResponse, error)
	ReportDASResult(ctx context.Context, in *MsgReportDASResult, opts ...grpc.CallOption) (*MsgReportDASResultResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RequestDAS(ctx context.Context, in *MsgRequestDAS, opts ...grpc.CallOption) (*MsgRequestDASResponse, error) {
	out := new(MsgRequestDASResponse)
	err := c.cc.Invoke(ctx, "/evmos.das.v1.Msg/RequestDAS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReportDASResult(ctx context.Context, in *MsgReportDASResult, opts ...grpc.CallOption) (*MsgReportDASResultResponse, error) {
	out := new(MsgReportDASResultResponse)
	err := c.cc.Invoke(ctx, "/evmos.das.v1.Msg/ReportDASResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RequestDAS(context.Context, *MsgRequestDAS) (*MsgRequestDASResponse, error)
	ReportDASResult(context.Context, *MsgReportDASResult) (*MsgReportDASResultResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RequestDAS(ctx context.Context, req *MsgRequestDAS) (*MsgRequestDASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDAS not implemented")
}
func (*UnimplementedMsgServer) ReportDASResult(ctx context.Context, req *MsgReportDASResult) (*MsgReportDASResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDASResult not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RequestDAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestDAS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestDAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.das.v1.Msg/RequestDAS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestDAS(ctx, req.(*MsgRequestDAS))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReportDASResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReportDASResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReportDASResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.das.v1.Msg/ReportDASResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReportDASResult(ctx, req.(*MsgReportDASResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.das.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDAS",
			Handler:    _Msg_RequestDAS_Handler,
		},
		{
			MethodName: "ReportDASResult",
			Handler:    _Msg_ReportDASResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmos/das/v1/tx.proto",
}

func (m *MsgRequestDAS) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestDAS) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestDAS) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumBlobs != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NumBlobs))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BatchHeaderHash) > 0 {
		i -= len(m.BatchHeaderHash)
		copy(dAtA[i:], m.BatchHeaderHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BatchHeaderHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestDASResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestDASResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestDASResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgReportDASResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReportDASResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReportDASResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Sampler) > 0 {
		i -= len(m.Sampler)
		copy(dAtA[i:], m.Sampler)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sampler)))
		i--
		dAtA[i] = 0x12
	}
	if m.RequestID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgReportDASResultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgReportDASResultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgReportDASResultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRequestDAS) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BatchHeaderHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.NumBlobs != 0 {
		n += 1 + sovTx(uint64(m.NumBlobs))
	}
	return n
}

func (m *MsgRequestDASResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestID != 0 {
		n += 1 + sovTx(uint64(m.RequestID))
	}
	return n
}

func (m *MsgReportDASResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestID != 0 {
		n += 1 + sovTx(uint64(m.RequestID))
	}
	l = len(m.Sampler)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Success {
		n += 2
	}
	return n
}

func (m *MsgReportDASResultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRequestDAS) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestDAS: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestDAS: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchHeaderHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchHeaderHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumBlobs", wireType)
			}
			m.NumBlobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumBlobs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestDASResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestDASResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestDASResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReportDASResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReportDASResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReportDASResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sampler", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sampler = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgReportDASResultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgReportDASResultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgReportDASResultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
