// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmos/committee/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryNextProposalIDRequest defines the request type for querying x/committee NextProposalID.
type QueryNextProposalIDRequest struct {
}

func (m *QueryNextProposalIDRequest) Reset()         { *m = QueryNextProposalIDRequest{} }
func (m *QueryNextProposalIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNextProposalIDRequest) ProtoMessage()    {}
func (*QueryNextProposalIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4b40beb2cbb1e09, []int{0}
}
func (m *QueryNextProposalIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNextProposalIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNextProposalIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNextProposalIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNextProposalIDRequest.Merge(m, src)
}
func (m *QueryNextProposalIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNextProposalIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNextProposalIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNextProposalIDRequest proto.InternalMessageInfo

// QueryNextProposalIDRequest defines the response type for querying x/committee NextProposalID.
type QueryNextProposalIDResponse struct {
	NextProposalID uint64 `protobuf:"varint,1,opt,name=next_proposal_id,json=nextProposalId,proto3" json:"next_proposal_id,omitempty"`
}

func (m *QueryNextProposalIDResponse) Reset()         { *m = QueryNextProposalIDResponse{} }
func (m *QueryNextProposalIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNextProposalIDResponse) ProtoMessage()    {}
func (*QueryNextProposalIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4b40beb2cbb1e09, []int{1}
}
func (m *QueryNextProposalIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNextProposalIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNextProposalIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNextProposalIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNextProposalIDResponse.Merge(m, src)
}
func (m *QueryNextProposalIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNextProposalIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNextProposalIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNextProposalIDResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryNextProposalIDRequest)(nil), "evmos.committee.v1.QueryNextProposalIDRequest")
	proto.RegisterType((*QueryNextProposalIDResponse)(nil), "evmos.committee.v1.QueryNextProposalIDResponse")
}

func init() { proto.RegisterFile("evmos/committee/v1/query.proto", fileDescriptor_e4b40beb2cbb1e09) }

var fileDescriptor_e4b40beb2cbb1e09 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x3f, 0x4b, 0x3b, 0x41,
	0x10, 0xbd, 0xfd, 0xf1, 0xd3, 0xe2, 0x8a, 0x20, 0x8b, 0x85, 0x39, 0xc3, 0x26, 0x04, 0x11, 0x0b,
	0x73, 0x4b, 0x14, 0xac, 0xac, 0x82, 0x8d, 0x85, 0xa2, 0x96, 0x5a, 0x84, 0x4b, 0x32, 0x9e, 0x0b,
	0xb9, 0x9d, 0x4b, 0x76, 0xee, 0x48, 0x5a, 0x3f, 0x81, 0xe0, 0x07, 0xb0, 0xf6, 0x9b, 0xa4, 0x0c,
	0xd8, 0x58, 0x89, 0x5e, 0xfc, 0x20, 0x72, 0x7f, 0x22, 0x1a, 0x23, 0xd8, 0x2c, 0x3b, 0xf3, 0xde,
	0xbc, 0x79, 0xf3, 0x6c, 0x01, 0x71, 0x80, 0x46, 0x76, 0x31, 0x08, 0x14, 0x11, 0x80, 0x8c, 0x9b,
	0x72, 0x10, 0xc1, 0x70, 0xec, 0x86, 0x43, 0x24, 0xe4, 0x3c, 0xc3, 0xdd, 0x4f, 0xdc, 0x8d, 0x9b,
	0x4e, 0xb9, 0x8b, 0x26, 0x40, 0xd3, 0xce, 0x18, 0x32, 0x2f, 0x72, 0xba, 0xb3, 0xee, 0xa3, 0x8f,
	0x79, 0x3f, 0xfd, 0x15, 0xdd, 0x8a, 0x8f, 0xe8, 0xf7, 0x41, 0x7a, 0xa1, 0x92, 0x9e, 0xd6, 0x48,
	0x1e, 0x29, 0xd4, 0xf3, 0x99, 0x72, 0x81, 0x66, 0x55, 0x27, 0xba, 0x96, 0x9e, 0x2e, 0xb6, 0x3b,
	0xd5, 0x45, 0x88, 0x54, 0x00, 0x86, 0xbc, 0x20, 0x2c, 0x08, 0xb5, 0x25, 0xf6, 0x7d, 0xd0, 0x60,
	0x54, 0xa1, 0x5e, 0xaf, 0xd8, 0xce, 0x79, 0x7a, 0xcf, 0x29, 0x8c, 0xe8, 0x6c, 0x88, 0x21, 0x1a,
	0xaf, 0x7f, 0x7c, 0x74, 0x01, 0x83, 0x08, 0x0c, 0xd5, 0xaf, 0xec, 0xcd, 0xa5, 0xa8, 0x09, 0x51,
	0x1b, 0xe0, 0x87, 0xf6, 0x9a, 0x86, 0x11, 0xa5, 0x97, 0x66, 0x50, 0x5b, 0xf5, 0x36, 0x58, 0x8d,
	0xed, 0xfc, 0x6f, 0xf1, 0xe4, 0xa5, 0x5a, 0x5a, 0x98, 0x2a, 0xe9, 0xaf, 0x75, 0x6f, 0xef, 0x91,
	0xd9, 0x2b, 0x99, 0x3a, 0x7f, 0x60, 0xf6, 0x02, 0x99, 0xbb, 0xee, 0xcf, 0x64, 0xdd, 0xdf, 0x9d,
	0x3a, 0xf2, 0xcf, 0xfc, 0xdc, 0x7b, 0x7d, 0xf7, 0xf6, 0xe9, 0xfd, 0xfe, 0xdf, 0x36, 0xdf, 0x92,
	0x4b, 0x32, 0x4a, 0x9d, 0x36, 0xe6, 0x57, 0x35, 0x54, 0xaf, 0x75, 0x32, 0x79, 0x13, 0xd6, 0x24,
	0x11, 0x6c, 0x9a, 0x08, 0xf6, 0x9a, 0x08, 0x76, 0x37, 0x13, 0xd6, 0x74, 0x26, 0xac, 0xe7, 0x99,
	0xb0, 0x2e, 0xa5, 0xaf, 0xe8, 0x26, 0xea, 0xa4, 0xcb, 0x0b, 0xb5, 0xfc, 0x8d, 0x9b, 0x07, 0x72,
	0xf4, 0x5d, 0x99, 0xc6, 0x21, 0x98, 0xce, 0x6a, 0x16, 0xfe, 0xfe, 0x47, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x3e, 0x17, 0xd8, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// NextProposalID queries the next proposal ID of the committee module.
	NextProposalID(ctx context.Context, in *QueryNextProposalIDRequest, opts ...grpc.CallOption) (*QueryNextProposalIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) NextProposalID(ctx context.Context, in *QueryNextProposalIDRequest, opts ...grpc.CallOption) (*QueryNextProposalIDResponse, error) {
	out := new(QueryNextProposalIDResponse)
	err := c.cc.Invoke(ctx, "/evmos.committee.v1.Query/NextProposalID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// NextProposalID queries the next proposal ID of the committee module.
	NextProposalID(context.Context, *QueryNextProposalIDRequest) (*QueryNextProposalIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) NextProposalID(ctx context.Context, req *QueryNextProposalIDRequest) (*QueryNextProposalIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextProposalID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_NextProposalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNextProposalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextProposalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.committee.v1.Query/NextProposalID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextProposalID(ctx, req.(*QueryNextProposalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.committee.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextProposalID",
			Handler:    _Query_NextProposalID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmos/committee/v1/query.proto",
}

func (m *QueryNextProposalIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNextProposalIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNextProposalIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryNextProposalIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNextProposalIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNextProposalIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextProposalID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NextProposalID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryNextProposalIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryNextProposalIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextProposalID != 0 {
		n += 1 + sovQuery(uint64(m.NextProposalID))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryNextProposalIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNextProposalIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNextProposalIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNextProposalIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNextProposalIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNextProposalIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextProposalID", wireType)
			}
			m.NextProposalID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextProposalID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
